### PR TITLE
support tracking_context in jwt token.

### PR DESCRIPTION
**Pull request by jimabramson**
XCOM-208

@clintonb @rlucioni please review.    The first commit will go away when #2 is merged.

### CODE REVIEW

**Comment by clintonb** [comment]
@jimabramson My rebasing for #2 threw things out of whack. Rebase on master, and we should be good to go.

**Comment by clintonb** [comment]
:+1:

**Comment by rlucioni** [comment]
If `tracking_context` remains a dictionary over in [#80](https://github.com/edx/ecommerce/pull/80), :+1:. If the JWT payload is kept flat, please update this accordingly.

**Comment by rlucioni** [comment]
I think this change warrants incrementing the version number in `setup.py`.

**Pull request merged**
