### PR TITLE
Automatically deploying new releases to PyPI

### PR DESCRIPTION
**Pull request by clintonb**
@rlucioni @feanil

### CODE REVIEW

**Comment by feanil** [comment]
:+1:

**Comment by rlucioni** [comment]
Already mentioned this in person, but Travis should upload a wheel for us in addition to a source distribution. See http://docs.travis-ci.com/user/deployment/pypi/#Uploading-different-distributions.

**Comment by clintonb** [comment]
FYI @feanil @rlucioni 

Three additional pushes directly to master later...it works!

The key was removing the whitelist from .travis.yaml so that TravisCI could run builds on tags: https://github.com/edx/ecommerce-api-client/compare/1.1.0...1.1.1.

**Comment by rlucioni** [comment]
@clintonb I assume you're referring to [this commit](https://github.com/edx/ecommerce-api-client/commit/0d84667fb7414b984a2cd3519c9f93d1178a149d). If so, this whitelist is what prevents us from running multiple builds per-PR.

**Comment by clintonb** [comment]
@rlucioni yeah. It's either multiple builds or automated uploads.

https://github.com/travis-ci/travis-ci/issues/2111

**Comment by rlucioni** [comment]
@clintonb that's a shame :disappointed:. Thanks for the info.

**Comment by feanil** [comment]
So I think the different builds are not bad to have.  They test the PR Branch and the merge of the PR branch to master right?

**Comment by clintonb** [comment]
@feanil that is correct.

**Comment by rlucioni** [comment]
@feanil good point; that actually seems like a good thing.

**Pull request merged**
